# k8s/api-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  ADMIN_API_KEY: "YWRtaW4tYXBpLWtleS0xMjM=" # base64 encoded "admin-api-key-123"
  USER_API_KEY: "dXNlci1hcGkta2V5LTQ1Ng==" # base64 encoded "user-api-key-456"
  SERVICE_API_KEY: "c2VydmljZS1hcGkta2V5LTc4OQ==" # base64 encoded "service-api-key-789"